on: [push]

name: ci

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - uses: actions/cache@master
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}
      - run: yarn install --network-concurrency 1
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}

  lint:
    name: Typescript lint
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - uses: actions/cache@master
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}
      - name: Run linting
        run: yarn lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - uses: actions/cache@master
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}

      - name: Run tests
        run: yarn test
